import MerchantCategory from "../models/MerchantCategory.js";
import { extractMerchant } from "./extractMerchant.js";

export const detectCategory = async (description, type, userId) => {
  if (type === "CREDIT") return "Income";

  const merchant = extractMerchant(description);

  // Check memory (DB)
  if (merchant) {
    const existing = await MerchantCategory.findOne({ userId, merchant });
    if (existing) return existing.category;
  }

  const desc = description.toLowerCase();

  const categoryMap = {
    Reimbursable: [
      "reimbursement",
      "reimbursed",
      "settlement",
      "splitwise",
      "shared expense",
      "payback",
      "paid back",
      "refund from friend",
      "returned money",
      "return money",
      "friend paid",
      "settled amount",
      "expense split",
      "split expense",
      "refund",
    ],
    Food: [
      "swiggy",
      "zomato",
      "restaurant",
      "bakery",
      "cafe",
      "pizza",
      "food",
      "tea",
      "coffee",
      "tiffin",
      "biryani",
      "juice",
      "dining",
      "mess",
      "snacks",
      "snack",
      "hotel",
      "eatery",
      "bakers",
      "ice cream",
      "chicken",
      "samosa",
      "catering",
      "masqati",
      "chat",
      "fruits",
      "fruit",
      "vegetables",
      "vegetable",
      "samosa",
      "milk",
    ],
    Groceries: [
      "grocery",
      "groceries",
      "supermarket",
      "mart",
      "dmart",
      "bigbasket",
      "blinkit",
      "zepto",
      "instamart",
      "vegetables",
      "fruits",
      "provision store",
      "kirana",
      "daily needs",
      "hypermarket",
    ],
    Travel: [
      "uber",
      "ola",
      "rapido",
      "fastag",
      "irctc",
      "bus",
      "train",
      "metro",
      "cab",
      "taxi",
      "auto",
      "petrol",
      "diesel",
      "fuel",
      "parking",
      "flight",
      "airport",
      "toll",
      "travel",
      "petrol",
      "discel",
      "passport",
    ],
    Shopping: [
      "amazon",
      "flipkart",
      "myntra",
      "meesho",
      "shop",
      "store",
      "mart",
      "mall",
      "purchase",
      "buy",
      "supermarket",
      "grocery",
      "dmart",
      "reliance trends",
      "ajio",
      "nykaa",
      "lifestyle",
      "fashions",
      "footwear",
      "traders",
      "jewellery",
    ],
    Bills: [
      "airtel",
      "jio",
      "electricity",
      "recharge",
      "bill",
      "broadband",
      "water",
      "gas",
      "wifi",
      "internet",
      "postpaid",
      "prepaid",
      "mobile recharged",
      "dth",
      "insurance",
      "utility",
      "phone bill",
      "current bill",
      "eb bill",
    ],
    Entertainment: [
      "netflix",
      "prime",
      "hotstar",
      "saavn",
      "spotify",
      "movie",
      "cinema",
      "game",
      "games",
      "bookmyshow",
      "youtube",
      "music",
      "subscription",
      "ott",
      "playstation",
      "xbox",
    ],
    Education: [
      "school",
      "college",
      "fee",
      "cbit",
      "tuition",
      "exam",
      "course",
      "academy",
      "training",
      "class",
      "classes",
      "university",
      "hostel fee",
      "library fee",
    ],
    Health: [
      "hospital",
      "medical",
      "pharmacy",
      "clinic",
      "doctor",
      "medicine",
      "medplus",
      "apollo",
      "diagnostic",
      "lab",
      "scan",
      "health",
      "care hospital",
      "dental",
    ],
  };

  for (const category in categoryMap) {
    for (const keyword of categoryMap[category]) {
      if (desc.includes(keyword)) return category;
    }
  }

  return null;
};
