import { createContext, useContext, useEffect, useMemo, useState } from "react";
import API from "../services/api";

const LanguageContext = createContext(null);

export const SUPPORTED_LANGUAGES = [
  { code: "en", label: "English" },
  { code: "te", label: "తెలుగు" },
  { code: "hi", label: "हिन्दी" },
  { code: "kn", label: "ಕನ್ನಡ" },
];

const translations = {
  en: {
    appName: "SpendSmart",
    navDashboard: "Dashboard",
    navReports: "Reports",
    navPdf: "PDF Upload",
    navBill: "Bill OCR",
    navSettings: "Settings",
    logout: "Logout",
    darkMode: "Dark Mode",
    lightMode: "Light Mode",
    settingsTitle: "Settings",
    settingsSubtitle: "Change your language any time without affecting your saved financial data.",
    languageLabel: "Preferred language",
    saveLanguage: "Save language",
    saving: "Saving...",
    languageSaved: "Language updated successfully.",
    chatTitle: "SpendSmart Assistant",
    chatPlaceholder: "Ask about reports, expenses, uploads, or settings...",
    send: "Send",
    askSuggestions: "Try asking",
    openPage: "Open page",
    loginHeadline: "Turn receipts, statements, and spending into a clear money story.",
    loginCopy: "Upload PDFs and bills, track trends over time, compare periods, and get a dashboard that actually helps you make better decisions.",
    welcomeBack: "Welcome back",
    loginCta: "Login",
    createAccount: "Create account",
    email: "Email",
    password: "Password",
    registerHeadline: "Build your own personal finance cockpit.",
    registerCopy: "Start with automated uploads, then explore category breakdowns, daily and monthly trends, and downloadable reports inside a dashboard built around clarity.",
    registerCta: "Register",
    name: "Name",
    backToLogin: "Back to login",
    dashboardHero: "See how your money is moving, where it goes, and what changed.",
    dashboardCopy: "Track spending trends, compare periods, and surface your most important money insights in one place.",
    totalExpense: "Total Expense",
    totalIncome: "Total Income",
    balance: "Balance",
    transactions: "Transactions",
    topCategory: "Top category",
    averageDailySpend: "Average daily spend",
    trendVsPrevious: "Trend vs previous period",
    recentTransactions: "Recent Transactions",
    latestItems: "Latest items from the selected range.",
    noTransactions: "No transactions found for this range.",
    reportsHero: "Explore trends by day, week, month, year, or your own custom range.",
    reportsCopy: "Compare current spending with previous periods, inspect category contribution, and export your report for offline reference.",
    exportPdf: "Export PDF",
    daily: "Daily",
    weekly: "Weekly",
    monthly: "Monthly",
    yearly: "Yearly",
    selectedRangeExpense: "Selected Range Expense",
    selectedRangeIncome: "Selected Range Income",
    categoryBreakdown: "Category Breakdown",
    contribution: "Contribution",
    uploadPdfHero: "Drop in a bank statement and let SpendSmart organize the hard part.",
    uploadPdfCopy: "Upload a PDF bank statement to extract transactions, skip duplicates, and push fresh spending data into your dashboard and reports.",
    uploadStatement: "Upload Statement",
    imported: "Imported",
    duplicatesSkipped: "Duplicates Skipped",
    needReview: "Need Review",
    categoryReview: "Category Review",
    categoryReviewCopy: "Any imported items that still need a category can be fixed here.",
    uploadBillHero: "Scan receipts and turn bill images into useful transaction data.",
    uploadBillCopy: "Upload a receipt image to extract description, amount, date, time, and field confidence before it lands in your reports.",
    uploadBill: "Upload Bill",
    processedSuccessfully: "Processed Successfully",
    needsReview: "Needs Review",
    description: "Description",
    amount: "Amount",
    category: "Category",
    date: "Date",
    time: "Time",
    source: "Source",
    confidence: "Confidence",
    missingFields: "Missing fields",
    lowConfidenceFields: "Low confidence fields",
    descriptionCandidates: "Description Candidates",
    amountCandidates: "Amount Candidates",
    ocrText: "OCR Text",
    choosePdf: "Choose a PDF statement",
    chooseBill: "Choose a bill image",
  },
  hi: {
    appName: "SpendSmart",
    navDashboard: "डैशबोर्ड",
    navReports: "रिपोर्ट्स",
    navPdf: "PDF अपलोड",
    navBill: "बिल OCR",
    navSettings: "सेटिंग्स",
    logout: "लॉगआउट",
    darkMode: "डार्क मोड",
    lightMode: "लाइट मोड",
    settingsTitle: "सेटिंग्स",
    settingsSubtitle: "अपनी भाषा कभी भी बदलें, इससे आपका सेव किया हुआ डेटा प्रभावित नहीं होगा।",
    languageLabel: "पसंदीदा भाषा",
    saveLanguage: "भाषा सेव करें",
    saving: "सेव हो रहा है...",
    languageSaved: "भाषा सफलतापूर्वक अपडेट हुई।",
    chatTitle: "SpendSmart सहायक",
    chatPlaceholder: "रिपोर्ट, खर्च, अपलोड या सेटिंग्स के बारे में पूछें...",
    send: "भेजें",
    askSuggestions: "यह पूछ कर देखें",
    loginHeadline: "रसीदों, स्टेटमेंट्स और खर्च को एक साफ़ कहानी में बदलें।",
    loginCopy: "PDF और बिल अपलोड करें, ट्रेंड्स देखें, पीरियड्स तुलना करें और उपयोगी डैशबोर्ड पाएं।",
    welcomeBack: "फिर से स्वागत है",
    loginCta: "लॉगिन",
    createAccount: "अकाउंट बनाएं",
    email: "ईमेल",
    password: "पासवर्ड",
    registerHeadline: "अपना व्यक्तिगत फाइनेंस कंट्रोल सेंटर बनाएं।",
    registerCopy: "ऑटोमेटेड अपलोड से शुरू करें, फिर कैटेगरी ब्रेकडाउन, ट्रेंड्स और डाउनलोडेबल रिपोर्ट्स देखें।",
    registerCta: "रजिस्टर",
    name: "नाम",
    backToLogin: "लॉगिन पर वापस जाएँ",
    dashboardHero: "देखें आपका पैसा कहाँ जा रहा है और क्या बदला है।",
    dashboardCopy: "खर्च के ट्रेंड्स देखें, पीरियड्स तुलना करें और महत्वपूर्ण इनसाइट्स एक जगह पाएं।",
    totalExpense: "कुल खर्च",
    totalIncome: "कुल आय",
    balance: "बैलेंस",
    transactions: "ट्रांजैक्शन्स",
    topCategory: "शीर्ष कैटेगरी",
    averageDailySpend: "औसत दैनिक खर्च",
    trendVsPrevious: "पिछले पीरियड से तुलना",
    recentTransactions: "हाल की ट्रांजैक्शन्स",
    latestItems: "चुनी गई तारीख सीमा की नवीनतम एंट्रियाँ।",
    noTransactions: "इस सीमा में कोई ट्रांजैक्शन नहीं मिला।",
    reportsHero: "दिन, सप्ताह, महीना, साल या अपनी पसंद की तारीख सीमा से ट्रेंड्स देखें।",
    reportsCopy: "वर्तमान खर्च की पिछले पीरियड से तुलना करें, कैटेगरी योगदान देखें और PDF एक्सपोर्ट करें।",
    exportPdf: "PDF एक्सपोर्ट",
    daily: "दैनिक",
    weekly: "साप्ताहिक",
    monthly: "मासिक",
    yearly: "वार्षिक",
    selectedRangeExpense: "चुनी गई सीमा का खर्च",
    selectedRangeIncome: "चुनी गई सीमा की आय",
    categoryBreakdown: "कैटेगरी ब्रेकडाउन",
    contribution: "योगदान",
    uploadPdfHero: "बैंक स्टेटमेंट डालें और SpendSmart बाकी काम संभाल लेगा।",
    uploadPdfCopy: "PDF स्टेटमेंट अपलोड करें ताकि ट्रांजैक्शन्स निकले, डुप्लिकेट हटें और रिपोर्ट्स अपडेट हों।",
    uploadStatement: "स्टेटमेंट अपलोड करें",
    imported: "इम्पोर्ट किया गया",
    duplicatesSkipped: "डुप्लिकेट छोड़े गए",
    needReview: "रीव्यू चाहिए",
    categoryReview: "कैटेगरी रीव्यू",
    categoryReviewCopy: "जिन इम्पोर्टेड आइटम्स को अभी भी कैटेगरी चाहिए, उन्हें यहाँ ठीक करें।",
    uploadBillHero: "रसीद स्कैन करें और बिल इमेज को उपयोगी ट्रांजैक्शन डेटा में बदलें।",
    uploadBillCopy: "रसीद इमेज अपलोड करें ताकि विवरण, राशि, तारीख, समय और कॉन्फिडेंस निकले।",
    uploadBill: "बिल अपलोड करें",
    processedSuccessfully: "सफलतापूर्वक प्रोसेस हुआ",
    needsReview: "रीव्यू चाहिए",
    description: "विवरण",
    amount: "राशि",
    category: "कैटेगरी",
    date: "तारीख",
    time: "समय",
    source: "स्रोत",
    confidence: "विश्वास स्तर",
    missingFields: "गुम फ़ील्ड्स",
    lowConfidenceFields: "कम कॉन्फिडेंस फ़ील्ड्स",
    descriptionCandidates: "विवरण विकल्प",
    amountCandidates: "राशि विकल्प",
    ocrText: "OCR टेक्स्ट",
    choosePdf: "PDF स्टेटमेंट चुनें",
    chooseBill: "बिल इमेज चुनें",
  },
  te: {
    appName: "SpendSmart",
    navDashboard: "డాష్‌బోర్డ్",
    navReports: "రిపోర్ట్స్",
    navPdf: "PDF అప్లోడ్",
    navBill: "బిల్ OCR",
    navSettings: "సెట్టింగ్స్",
    logout: "లాగౌట్",
    darkMode: "డార్క్ మోడ్",
    lightMode: "లైట్ మోడ్",
    settingsTitle: "సెట్టింగ్స్",
    settingsSubtitle: "సేవ్ చేసిన డేటా మారకుండా మీరు ఎప్పుడైనా భాష మార్చవచ్చు.",
    languageLabel: "ఇష్టమైన భాష",
    saveLanguage: "భాషను సేవ్ చేయండి",
    saving: "సేవ్ అవుతోంది...",
    languageSaved: "భాష విజయవంతంగా అప్డేట్ అయింది.",
    chatTitle: "SpendSmart అసిస్టెంట్",
    chatPlaceholder: "రిపోర్ట్స్, ఖర్చులు, అప్లోడ్స్ లేదా సెట్టింగ్స్ గురించి అడగండి...",
    send: "పంపండి",
    askSuggestions: "ఇవి అడగండి",
    loginHeadline: "రసీదులు, స్టేట్‌మెంట్లు, ఖర్చులను స్పష్టమైన మనీ స్టోరీగా మార్చండి.",
    loginCopy: "PDFలు, బిల్లులు అప్లోడ్ చేయండి, ట్రెండ్స్ చూడండి, పీరియడ్స్ పోల్చండి, ఉపయోగకరమైన డాష్‌బోర్డ్ పొందండి.",
    welcomeBack: "మళ్లీ స్వాగతం",
    loginCta: "లాగిన్",
    createAccount: "ఖాతా సృష్టించండి",
    email: "ఇమెయిల్",
    password: "పాస్‌వర్డ్",
    registerHeadline: "మీ స్వంత ఫైనాన్స్ కాక్‌పిట్ నిర్మించండి.",
    registerCopy: "ఆటోమేటెడ్ అప్లోడ్స్‌తో మొదలు పెట్టి, కేటగిరీ బ్రేక్‌డౌన్‌లు, ట్రెండ్స్, డౌన్‌లోడ్ చేయగల రిపోర్ట్స్ చూడండి.",
    registerCta: "రిజిస్టర్",
    name: "పేరు",
    backToLogin: "లాగిన్‌కు తిరిగి వెళ్ళండి",
    dashboardHero: "మీ డబ్బు ఎలా కదులుతోంది, ఎక్కడ ఖర్చవుతోంది, ఏమి మారిందో చూడండి.",
    dashboardCopy: "ఖర్చు ట్రెండ్స్, పీరియడ్ పోలికలు, ముఖ్యమైన ఫైనాన్స్ ఇన్‌సైట్స్ అన్నీ ఒకేచోట చూడండి.",
    totalExpense: "మొత్తం ఖర్చు",
    totalIncome: "మొత్తం ఆదాయం",
    balance: "బ్యాలెన్స్",
    transactions: "ట్రాన్సాక్షన్లు",
    topCategory: "అత్యధిక కేటగిరీ",
    averageDailySpend: "సగటు రోజువారీ ఖర్చు",
    trendVsPrevious: "గత పీరియడ్‌తో పోలిక",
    recentTransactions: "తాజా ట్రాన్సాక్షన్లు",
    latestItems: "ఎంచుకున్న తేదీ పరిధిలో తాజా అంశాలు.",
    noTransactions: "ఈ పరిధిలో ట్రాన్సాక్షన్లు లేవు.",
    reportsHero: "రోజు, వారం, నెల, సంవత్సరం లేదా మీకు నచ్చిన తేదీ పరిధిలో ట్రెండ్స్ చూడండి.",
    reportsCopy: "ప్రస్తుత ఖర్చును గత పీరియడ్‌తో పోల్చండి, కేటగిరీ వాటాను చూడండి, PDF ఎగుమతి చేయండి.",
    exportPdf: "PDF ఎగుమతి",
    daily: "రోజువారీ",
    weekly: "వారానికొకసారి",
    monthly: "నెలవారీ",
    yearly: "సంవత్సరవారీ",
    selectedRangeExpense: "ఎంచుకున్న పరిధి ఖర్చు",
    selectedRangeIncome: "ఎంచుకున్న పరిధి ఆదాయం",
    categoryBreakdown: "కేటగిరీ విభజన",
    contribution: "వాటా",
    uploadPdfHero: "బ్యాంక్ స్టేట్‌మెంట్ వేయండి, మిగతా పని SpendSmart చూసుకుంటుంది.",
    uploadPdfCopy: "PDF స్టేట్‌మెంట్ అప్లోడ్ చేసి ట్రాన్సాక్షన్లు తీయండి, డుప్లికేట్లు తీసేయండి, రిపోర్ట్స్ అప్డేట్ చేయండి.",
    uploadStatement: "స్టేట్‌మెంట్ అప్లోడ్",
    imported: "ఇంపోర్ట్ అయ్యాయి",
    duplicatesSkipped: "డుప్లికేట్లు దాటివేయబడ్డాయి",
    needReview: "రివ్యూ అవసరం",
    categoryReview: "కేటగిరీ రివ్యూ",
    categoryReviewCopy: "ఇంకా కేటగిరీ అవసరమైన ఇంపోర్ట్ చేసిన అంశాలను ఇక్కడ సరిచేయండి.",
    uploadBillHero: "రసీదులను స్కాన్ చేసి బిల్ చిత్రాలను ఉపయోగకరమైన డేటాగా మార్చండి.",
    uploadBillCopy: "రసీదు ఇమేజ్ అప్లోడ్ చేసి వివరణ, మొత్తం, తేదీ, సమయం, నమ్మకం స్థాయి పొందండి.",
    uploadBill: "బిల్ అప్లోడ్",
    processedSuccessfully: "విజయవంతంగా పూర్తైంది",
    needsReview: "రివ్యూ అవసరం",
    description: "వివరణ",
    amount: "మొత్తం",
    category: "కేటగిరీ",
    date: "తేదీ",
    time: "సమయం",
    source: "మూలం",
    confidence: "నమ్మకం స్థాయి",
    missingFields: "లేని ఫీల్డ్స్",
    lowConfidenceFields: "తక్కువ నమ్మకం ఫీల్డ్స్",
    descriptionCandidates: "వివరణ ఎంపికలు",
    amountCandidates: "మొత్తం ఎంపికలు",
    ocrText: "OCR టెక్స్ట్",
    choosePdf: "PDF స్టేట్‌మెంట్ ఎంచుకోండి",
    chooseBill: "బిల్ ఇమేజ్ ఎంచుకోండి",
  },
  kn: {
    appName: "SpendSmart",
    navDashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    navReports: "ವರದಿಗಳು",
    navPdf: "PDF ಅಪ್ಲೋಡ್",
    navBill: "ಬಿಲ್ OCR",
    navSettings: "ಸೆಟ್ಟಿಂಗ್ಸ್",
    logout: "ಲಾಗ್‌ಔಟ್",
    darkMode: "ಡಾರ್ಕ್ ಮೋಡ್",
    lightMode: "ಲೈಟ್ ಮೋಡ್",
    settingsTitle: "ಸೆಟ್ಟಿಂಗ್ಸ್",
    settingsSubtitle: "ನಿಮ್ಮ ಉಳಿಸಿದ ಡೇಟಾಗೆ ಪರಿಣಾಮ ಬಾರದೆ ನೀವು ಯಾವಾಗ ಬೇಕಾದರೂ ಭಾಷೆ ಬದಲಾಯಿಸಬಹುದು.",
    languageLabel: "ಆದ್ಯ ಭಾಷೆ",
    saveLanguage: "ಭಾಷೆ ಉಳಿಸಿ",
    saving: "ಉಳಿಸುತ್ತಿದೆ...",
    languageSaved: "ಭಾಷೆ ಯಶಸ್ವಿಯಾಗಿ ನವೀಕರಿಸಲಾಗಿದೆ.",
    chatTitle: "SpendSmart ಸಹಾಯಕ",
    chatPlaceholder: "ವರದಿಗಳು, ಖರ್ಚುಗಳು, ಅಪ್ಲೋಡ್‌ಗಳು ಅಥವಾ ಸೆಟ್ಟಿಂಗ್ಸ್ ಬಗ್ಗೆ ಕೇಳಿ...",
    send: "ಕಳುಹಿಸಿ",
    askSuggestions: "ಇವು ಕೇಳಿ",
    loginHeadline: "ರಸೀದಿಗಳು, ಸ್ಟೇಟ್ಮೆಂಟ್‌ಗಳು ಮತ್ತು ಖರ್ಚುಗಳನ್ನು ಸ್ಪಷ್ಟವಾದ ಹಣಕಾಸು ಕಥೆಯಾಗಿ ಮಾಡಿ.",
    loginCopy: "PDF ಮತ್ತು ಬಿಲ್‌ಗಳನ್ನು ಅಪ್ಲೋಡ್ ಮಾಡಿ, ಟ್ರೆಂಡ್ಸ್ ನೋಡಿ, ಅವಧಿಗಳನ್ನು ಹೋಲಿಸಿ ಮತ್ತು ಉಪಯುಕ್ತ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್ ಪಡೆಯಿರಿ.",
    welcomeBack: "ಮತ್ತೆ ಸ್ವಾಗತ",
    loginCta: "ಲಾಗಿನ್",
    createAccount: "ಖಾತೆ ರಚಿಸಿ",
    email: "ಇಮೇಲ್",
    password: "ಪಾಸ್‌ವರ್ಡ್",
    registerHeadline: "ನಿಮ್ಮದೇ ವೈಯಕ್ತಿಕ ಹಣಕಾಸು ಕಾಕ್‌ಪಿಟ್ ನಿರ್ಮಿಸಿ.",
    registerCopy: "ಸ್ವಯಂಚಾಲಿತ ಅಪ್ಲೋಡ್‌ಗಳಿಂದ ಪ್ರಾರಂಭಿಸಿ, ನಂತರ ವರ್ಗ ವಿಭಜನೆಗಳು, ಟ್ರೆಂಡ್ಸ್ ಮತ್ತು ಡೌನ್‌ಲೋಡ್ ವರದಿಗಳನ್ನು ನೋಡಿ.",
    registerCta: "ನೋಂದಣಿ",
    name: "ಹೆಸರು",
    backToLogin: "ಲಾಗಿನ್‌ಗೆ ಹಿಂತಿರುಗಿ",
    dashboardHero: "ನಿಮ್ಮ ಹಣ ಹೇಗೆ ಚಲಿಸುತ್ತಿದೆ, ಎಲ್ಲಿಗೆ ಹೋಗುತ್ತಿದೆ, ಏನು ಬದಲಾಗಿದೆ ನೋಡಿ.",
    dashboardCopy: "ಖರ್ಚಿನ ಟ್ರೆಂಡ್ಸ್, ಅವಧಿ ಹೋಲಿಕೆಗಳು ಮತ್ತು ಮುಖ್ಯ ಹಣಕಾಸು ಇನ್ಸೈಟ್ಸ್ ಒಂದೇ ಸ್ಥಳದಲ್ಲಿ ನೋಡಿ.",
    totalExpense: "ಒಟ್ಟು ಖರ್ಚು",
    totalIncome: "ಒಟ್ಟು ಆದಾಯ",
    balance: "ಬ್ಯಾಲೆನ್ಸ್",
    transactions: "ವಹಿವಾಟುಗಳು",
    topCategory: "ಮುಖ್ಯ ವರ್ಗ",
    averageDailySpend: "ಸರಾಸರಿ ದೈನಂದಿನ ಖರ್ಚು",
    trendVsPrevious: "ಹಿಂದಿನ ಅವಧಿಯೊಂದಿಗೆ ಹೋಲಿಕೆ",
    recentTransactions: "ಇತ್ತೀಚಿನ ವಹಿವಾಟುಗಳು",
    latestItems: "ಆಯ್ಕೆ ಮಾಡಿದ ಅವಧಿಯ ಇತ್ತೀಚಿನ ಅಂಶಗಳು.",
    noTransactions: "ಈ ಅವಧಿಗೆ ಯಾವುದೇ ವಹಿವಾಟುಗಳಿಲ್ಲ.",
    reportsHero: "ದಿನ, ವಾರ, ತಿಂಗಳು, ವರ್ಷ ಅಥವಾ ನಿಮ್ಮದೇ ದಿನಾಂಕ ವ್ಯಾಪ್ತಿಯಲ್ಲಿ ಟ್ರೆಂಡ್ಸ್ ನೋಡಿ.",
    reportsCopy: "ಪ್ರಸ್ತುತ ಖರ್ಚನ್ನು ಹಿಂದಿನ ಅವಧಿಯೊಂದಿಗೆ ಹೋಲಿಸಿ, ವರ್ಗ ಕೊಡುಗೆ ನೋಡಿ ಮತ್ತು PDF ಎಕ್ಸ್‌ಪೋರ್ಟ್ ಮಾಡಿ.",
    exportPdf: "PDF ಎಕ್ಸ್‌ಪೋರ್ಟ್",
    daily: "ದೈನಂದಿನ",
    weekly: "ವಾರದ",
    monthly: "ಮಾಸಿಕ",
    yearly: "ವಾರ್ಷಿಕ",
    selectedRangeExpense: "ಆಯ್ಕೆ ಮಾಡಿದ ಅವಧಿಯ ಖರ್ಚು",
    selectedRangeIncome: "ಆಯ್ಕೆ ಮಾಡಿದ ಅವಧಿಯ ಆದಾಯ",
    categoryBreakdown: "ವರ್ಗ ವಿಭಜನೆ",
    contribution: "ಕೊಡುಗೆ",
    uploadPdfHero: "ಬ್ಯಾಂಕ್ ಸ್ಟೇಟ್ಮೆಂಟ್ ಹಾಕಿ, ಉಳಿದ ಕೆಲಸ SpendSmart ನೋಡಿಕೊಳ್ಳುತ್ತದೆ.",
    uploadPdfCopy: "PDF ಸ್ಟೇಟ್ಮೆಂಟ್ ಅಪ್ಲೋಡ್ ಮಾಡಿ, ವಹಿವಾಟುಗಳನ್ನು ತೆಗೆಯಿರಿ, ಡುಪ್ಲಿಕೇಟುಗಳನ್ನು ತಪ್ಪಿಸಿ, ವರದಿಗಳನ್ನು ನವೀಕರಿಸಿ.",
    uploadStatement: "ಸ್ಟೇಟ್ಮೆಂಟ್ ಅಪ್ಲೋಡ್",
    imported: "ಆಮದುಗೊಂಡವು",
    duplicatesSkipped: "ಡುಪ್ಲಿಕೇಟುಗಳು ಬಿಟ್ಟವು",
    needReview: "ಪರಿಶೀಲನೆ ಬೇಕು",
    categoryReview: "ವರ್ಗ ಪರಿಶೀಲನೆ",
    categoryReviewCopy: "ಇನ್ನೂ ವರ್ಗ ಬೇಕಿರುವ ಆಮದುಗೊಂಡ ಅಂಶಗಳನ್ನು ಇಲ್ಲಿ ಸರಿಪಡಿಸಿ.",
    uploadBillHero: "ರಸೀದಿಗಳನ್ನು ಸ್ಕ್ಯಾನ್ ಮಾಡಿ ಮತ್ತು ಚಿತ್ರಗಳನ್ನು ಉಪಯುಕ್ತ ವಹಿವಾಟು ಡೇಟಾವಾಗಿ ಮಾಡಿ.",
    uploadBillCopy: "ರಸೀದಿ ಚಿತ್ರವನ್ನು ಅಪ್ಲೋಡ್ ಮಾಡಿ, ವಿವರಣೆ, ಮೊತ್ತ, ದಿನಾಂಕ, ಸಮಯ ಮತ್ತು ವಿಶ್ವಾಸಮಟ್ಟ ಪಡೆಯಿರಿ.",
    uploadBill: "ಬಿಲ್ ಅಪ್ಲೋಡ್",
    processedSuccessfully: "ಯಶಸ್ವಿಯಾಗಿ ಪ್ರೊಸೆಸ್ ಆಯಿತು",
    needsReview: "ಪರಿಶೀಲನೆ ಬೇಕು",
    description: "ವಿವರಣೆ",
    amount: "ಮೊತ್ತ",
    category: "ವರ್ಗ",
    date: "ದಿನಾಂಕ",
    time: "ಸಮಯ",
    source: "ಮೂಲ",
    confidence: "ವಿಶ್ವಾಸಮಟ್ಟ",
    missingFields: "ಕಾಣೆಯಾದ ಫೀಲ್ಡ್‌ಗಳು",
    lowConfidenceFields: "ಕಡಿಮೆ ವಿಶ್ವಾಸ ಫೀಲ್ಡ್‌ಗಳು",
    descriptionCandidates: "ವಿವರಣೆ ಆಯ್ಕೆಗಳು",
    amountCandidates: "ಮೊತ್ತ ಆಯ್ಕೆಗಳು",
    ocrText: "OCR ಪಠ್ಯ",
    choosePdf: "PDF ಸ್ಟೇಟ್ಮೆಂಟ್ ಆಯ್ಕೆಮಾಡಿ",
    chooseBill: "ಬಿಲ್ ಚಿತ್ರ ಆಯ್ಕೆಮಾಡಿ",
  },
};

const supplementalTranslations = {
  en: {
    navManual: "Manual Entry",
    navGoals: "Goals",
    navProfile: "Profile",
    themeToggleLabel: "Toggle theme",
    loginPill: "SpendSmart Analytics",
    loginThemeLight: "Green Light Theme",
    loginThemeDark: "Deep Green Night Theme",
    loginPanelCopy: "Log in to view your financial dashboard, reports, and upload tools.",
    loginFailed: "Login failed",
    registerPill: "Create Your Workspace",
    registerThemeLight: "Fresh Green Mode",
    registerThemeDark: "Forest Dark Mode",
    registerPanelCopy: "Register once, then log in to access the dashboard and report center.",
    registerSuccess: "Registered successfully",
    registrationFailed: "Registration failed",
    dashboardLoadTitle: "Loading dashboard...",
    dashboardLoadCopy: "Crunching your latest financial trends.",
    dashboardUnavailable: "Dashboard unavailable",
    allCategories: "All categories",
    showGoals: "Show Goals",
    hideGoals: "Hide Goals",
    dashboardGoalsTitle: "Goals Snapshot",
    dashboardGoalsCopy: "Track your active goals directly from the dashboard.",
    financialCommandCenter: "Financial Analyzer",
    financialHealthScore: "Financial Health Score",
    notEnoughData: "Not enough data",
    whyThisScore: "Why this score?",
    savingsRatio: "Savings ratio",
    overspendingFrequency: "Overspending frequency",
    categoryBalanceScore: "Category balance",
    noSpendingData: "No spending data",
    dailyTrendTitle: "Daily Trend",
    dailyTrendSubtitle: "Daily expenses and income in the selected date range.",
    weeklyViewTitle: "Weekly View",
    weeklyViewSubtitle: "Weekly grouped movement for quick pattern recognition.",
    incomeExpenseSnapshotTitle: "Income / Expense Snapshot",
    incomeExpenseSnapshotSubtitle: "Compare your current range against the previous period.",
    reportsUnavailable: "Reports unavailable",
    financialReports: "Financial Reports",
    reportsLoadingTitle: "Loading reports...",
    reportsLoadingCopy: "Preparing trends and financial comparisons.",
    currentLabel: "Current",
    previousLabel: "Previous",
    changeLabel: "Change",
    trendTitleSuffix: "Trend",
    trendSelectedRangeSubtitle: "Trend breakdown for the selected custom date range.",
    monthlySummaryTitle: "Monthly Summary",
    monthlySummarySubtitle: "Month-wise overview inside the selected range.",
    periodComparisonTitle: "Period Comparison",
    trendUp: "up",
    trendDown: "down",
    trendFlat: "flat",
    totalExpensesShare: "of total expenses",
    goalsHeroPill: "Goal-Based Saving Planner",
    goalsHeroTitle: "Turn future purchases into a clear monthly saving plan.",
    goalsHeroCopy: "Add a goal like laptop, bike, travel, or emergency fund. SpendSmart calculates how much you need to save every month based on your target amount, what you already saved, and your deadline.",
    editGoalPlan: "Edit Goal Plan",
    createGoalPlan: "Create Goal Plan",
    editGoalCopy: "Update the saved amount or target details whenever you make progress.",
    createGoalCopy: "Set a target amount, deadline, and how much you already saved.",
    cancelEdit: "Cancel Edit",
    goalTitlePlaceholder: "Goal title",
    targetAmountPlaceholder: "Target amount",
    currentSavedPlaceholder: "Already saved",
    notesPlaceholder: "Notes (optional)",
    updateGoal: "Update Goal",
    createPlan: "Create Plan",
    goalUpdated: "Goal updated successfully.",
    goalCreated: "Goal plan created successfully.",
    goalsLoadFailed: "Failed to load goals",
    goalUpdateFailed: "Failed to update goal",
    goalCreateFailed: "Failed to create goal",
    goalDeleteFailed: "Failed to delete goal",
    savedGreaterThanTarget: "Already saved amount cannot be greater than the target amount.",
    plannerPreview: "Planner Preview",
    remaining: "Remaining",
    monthsLeft: "Months Left",
    savePerMonth: "Save Per Month",
    mySavingGoals: "My Saving Goals",
    mySavingGoalsCopy: "Track your targets and see how much you need to save each month to stay on pace.",
    loadingGoals: "Loading your goals...",
    daysRemaining: "days remaining",
    progress: "Progress",
    targetBy: "Target",
    saved: "Saved",
    complete: "complete",
    monthlyPlan: "Monthly Plan",
    monthsLeftSuffix: "months left",
    edit: "Edit",
    delete: "Delete",
    noGoalsYet: "No saving goals yet. Create your first plan above.",
    manualEntryPill: "Manual Entry",
    manualEntryHero: "Add a transaction yourself whenever you need a quick correction or cash record.",
    manualEntryCopy: "Enter the transaction details below. If you leave the date or time empty, SpendSmart will use the current system date and time automatically.",
    descriptionRequired: "Description is required.",
    validAmountRequired: "Enter a valid amount.",
    addTransactionFailed: "Unable to add transaction.",
    descriptionLabel: "Description",
    amountLabel: "Amount",
    typeLabel: "Type",
    dateLabel: "Date",
    timeLabel: "Time",
    categoryLabel: "Category",
    descriptionPlaceholder: "Paid to bakery, salary credited, cash purchase...",
    debit: "Debit",
    credit: "Credit",
    autoDetect: "Auto-detect",
    addTransaction: "Add Transaction",
    transactionAdded: "Transaction added successfully",
    statementImport: "Statement Import",
    selectPdfFirst: "Select a PDF bank statement first.",
    uploadFailed: "Upload failed",
    exportFailed: "Failed to export report",
    onlyPdfAccepted: "Only PDF files are accepted.",
    billOcrPill: "Bill OCR",
    selectBillFirst: "Select a bill image first.",
    billUploadFailed: "Bill upload failed",
    imageFormatsHelp: "JPG, PNG, and WEBP images work best.",
    appearance: "Appearance",
    appearanceCopy: "Switch between light and dark mode any time from here.",
    uploadedFilesTitle: "PDFs",
    uploadedFilesCopy: "See every statement and bill you uploaded, and remove files with all extracted data when needed.",
    uploadedFilesLoadFailed: "Failed to load uploaded PDFs.",
    uploadedFileDeleted: "Uploaded file and extracted data deleted successfully.",
    uploadedFileDeleteFailed: "Failed to delete uploaded file.",
    loadingUploadedFiles: "Loading uploaded PDFs...",
    noUploadedFiles: "No uploaded PDFs or bills yet.",
    profileTitle: "Profile",
    profileSubtitle: "Manage your account details and review uploaded files and manual transactions.",
    profileLoadingTitle: "Loading profile...",
    profileLoadingCopy: "Fetching your account and file history.",
    profileLoadFailed: "Unable to load profile details right now.",
    profilePdfsTitle: "PDFs",
    profilePdfsCopy: "Your uploaded bank statements.",
    profileBillsTitle: "Bills",
    profileBillsCopy: "Your uploaded receipt and bill images.",
    profileManualTitle: "Manual Transactions",
    profileManualCopy: "Transactions you added manually.",
    uploadedOn: "Uploaded on",
    transactionRange: "Transaction range",
    showLess: "Show Less",
    noManualTransactions: "No manual transactions found.",
    manualEditTitle: "Edit Manual Transactions",
    manualEditCopy: "Only manual entries are editable. Imported PDF/BILL entries are read-only.",
    manualLoadFailed: "Unable to load manual transactions.",
    manualUpdated: "Manual transaction updated successfully.",
    manualUpdateFailed: "Failed to update manual transaction.",
    editManualEntry: "Edit Manual Entry",
    saveChanges: "Save Changes",
    manualTransactionDetails: "Manual Transaction Details",
    loading: "Loading...",
    noCategoryData: "No category data available for this range.",
    categoryShareTitle: "Category Share",
    categoryShareSubtitle: "Percentage contribution of each expense category.",
    spendLegend: "Spend",
    noTrendData: "No trend data available for this range.",
    trendOverviewTitle: "Trend Overview",
    trendOverviewSubtitle: "Expense and income movement over time.",
    expenseSeries: "Expense",
    incomeSeries: "Income",
    noComparisonData: "No comparison data available.",
    comparisonSnapshotTitle: "Comparison Snapshot",
    comparisonSnapshotSubtitle: "Quick comparison for the selected period.",
    updated: "Updated",
    noUncategorizedTransactions: "No uncategorized transactions right now.",
    uncategorizedTransactionsTitle: "Uncategorized Transactions",
    uncategorizedTransactionsHelp: "Assign categories later and they will move into category reports automatically.",
    select: "Select",
    viewMore: "View More",
    showRecent: "Show Recent",
    loadMore: "Load More",
    filterAll: "All",
    filterCategoryWise: "Category-wise",
    filterUncategorized: "Uncategorized",
    smartInsightsSummaryTitle: "Smart Insights Summary",
    smartInsightsSummaryFallback: "No data available",
    assistantUnavailable: "Assistant is unavailable right now.",
    chatSuggestionsList: "Reports, monthly expenses, why did I spend more, unusual transactions, saving suggestions.",
    openPage: "Open page",
    categoryFood: "Food",
    categoryGroceries: "Groceries",
    categoryTravel: "Travel",
    categoryShopping: "Shopping",
    categoryBills: "Bills",
    categoryEntertainment: "Entertainment",
    categoryEducation: "Education",
    categoryHealth: "Health",
    categoryReimbursable: "Reimbursable",
    categoryIncome: "Income",
    categoryUncategorized: "Uncategorized",
    healthExcellent: "Excellent",
    healthHealthy: "Healthy",
    healthNeedsAttention: "Needs Attention",
    healthAtRisk: "At Risk",
    healthNoData: "No data available",
    documentPdf: "PDF",
    documentBill: "Bill",
    view: "View",
    previewTitle: "Preview",
    previewLoading: "Loading preview...",
    previewUnavailable: "Preview is unavailable for this file right now.",
    closePreview: "Close Preview",
  },
  hi: {
    navManual: "मैनुअल एंट्री",
    navGoals: "लक्ष्य",
    loginPill: "SpendSmart एनालिटिक्स",
    loginThemeLight: "ग्रीन लाइट थीम",
    loginThemeDark: "डीप ग्रीन नाइट थीम",
    loginPanelCopy: "अपना वित्तीय डैशबोर्ड, रिपोर्ट्स और अपलोड टूल्स देखने के लिए लॉग इन करें।",
    loginFailed: "लॉगिन विफल हुआ",
    registerPill: "अपना वर्कस्पेस बनाएं",
    registerThemeLight: "फ्रेश ग्रीन मोड",
    registerThemeDark: "फॉरेस्ट डार्क मोड",
    registerPanelCopy: "एक बार रजिस्टर करें, फिर डैशबोर्ड और रिपोर्ट केंद्र तक पहुंचें।",
    registerSuccess: "सफलतापूर्वक रजिस्टर हो गया",
    registrationFailed: "रजिस्ट्रेशन विफल हुआ",
    dashboardLoadTitle: "डैशबोर्ड लोड हो रहा है...",
    dashboardLoadCopy: "आपके नवीनतम वित्तीय ट्रेंड्स तैयार किए जा रहे हैं।",
    dashboardUnavailable: "डैशबोर्ड उपलब्ध नहीं है",
    financialCommandCenter: "वित्तीय कमांड सेंटर",
    financialHealthScore: "वित्तीय स्वास्थ्य स्कोर",
    notEnoughData: "पर्याप्त डेटा नहीं है",
    whyThisScore: "यह स्कोर क्यों?",
    savingsRatio: "बचत अनुपात",
    overspendingFrequency: "अधिक खर्च की आवृत्ति",
    categoryBalanceScore: "श्रेणी संतुलन",
    noSpendingData: "खर्च का डेटा नहीं है",
    dailyTrendTitle: "दैनिक ट्रेंड",
    dailyTrendSubtitle: "चुनी हुई तिथि सीमा में दैनिक खर्च और आय।",
    weeklyViewTitle: "साप्ताहिक दृश्य",
    weeklyViewSubtitle: "तेज़ पैटर्न पहचान के लिए साप्ताहिक समूहित गतिविधि।",
    incomeExpenseSnapshotTitle: "आय / खर्च स्नैपशॉट",
    incomeExpenseSnapshotSubtitle: "वर्तमान सीमा की पिछले पीरियड से तुलना करें।",
    reportsUnavailable: "रिपोर्ट्स उपलब्ध नहीं हैं",
    financialReports: "वित्तीय रिपोर्ट्स",
    reportsLoadingTitle: "रिपोर्ट्स लोड हो रही हैं...",
    reportsLoadingCopy: "ट्रेंड्स और वित्तीय तुलना तैयार की जा रही है।",
    currentLabel: "वर्तमान",
    previousLabel: "पिछला",
    changeLabel: "बदलाव",
    trendTitleSuffix: "ट्रेंड",
    trendSelectedRangeSubtitle: "चुनी हुई कस्टम तिथि सीमा के लिए ट्रेंड विवरण।",
    monthlySummaryTitle: "मासिक सारांश",
    monthlySummarySubtitle: "चुनी हुई सीमा के भीतर माहवार अवलोकन।",
    periodComparisonTitle: "अवधि तुलना",
    trendUp: "ऊपर",
    trendDown: "नीचे",
    trendFlat: "समान",
    totalExpensesShare: "कुल खर्च का",
    goalsHeroPill: "लक्ष्य-आधारित बचत योजनाकार",
    goalsHeroTitle: "भविष्य की खरीद को स्पष्ट मासिक बचत योजना में बदलें।",
    goalsHeroCopy: "लैपटॉप, बाइक, यात्रा या इमरजेंसी फंड जैसा लक्ष्य जोड़ें। SpendSmart आपकी लक्ष्य राशि, अभी तक बचाई गई राशि और समयसीमा के आधार पर बताता है कि हर महीने कितना बचाना है।",
    editGoalPlan: "लक्ष्य योजना संपादित करें",
    createGoalPlan: "लक्ष्य योजना बनाएं",
    editGoalCopy: "प्रगति होने पर बचाई गई राशि या लक्ष्य विवरण अपडेट करें।",
    createGoalCopy: "लक्ष्य राशि, समयसीमा और अभी तक बचाई गई राशि सेट करें।",
    cancelEdit: "संपादन रद्द करें",
    goalTitlePlaceholder: "लक्ष्य शीर्षक",
    targetAmountPlaceholder: "लक्ष्य राशि",
    currentSavedPlaceholder: "पहले से बचाई गई राशि",
    notesPlaceholder: "नोट्स (वैकल्पिक)",
    updateGoal: "लक्ष्य अपडेट करें",
    createPlan: "योजना बनाएं",
    goalUpdated: "लक्ष्य सफलतापूर्वक अपडेट हुआ।",
    goalCreated: "लक्ष्य योजना सफलतापूर्वक बनी।",
    goalsLoadFailed: "लक्ष्य लोड नहीं हो सके",
    goalUpdateFailed: "लक्ष्य अपडेट नहीं हो सका",
    goalCreateFailed: "लक्ष्य बनाया नहीं जा सका",
    goalDeleteFailed: "लक्ष्य हटाया नहीं जा सका",
    savedGreaterThanTarget: "पहले से बचाई गई राशि लक्ष्य राशि से अधिक नहीं हो सकती।",
    plannerPreview: "योजना पूर्वावलोकन",
    remaining: "शेष",
    monthsLeft: "महीने बचे",
    savePerMonth: "प्रति माह बचत",
    mySavingGoals: "मेरे बचत लक्ष्य",
    mySavingGoalsCopy: "अपने लक्ष्यों को ट्रैक करें और देखें कि सही गति बनाए रखने के लिए हर महीने कितना बचाना है।",
    loadingGoals: "आपके लक्ष्य लोड हो रहे हैं...",
    targetBy: "लक्ष्य",
    saved: "बचाया गया",
    complete: "पूर्ण",
    monthlyPlan: "मासिक योजना",
    monthsLeftSuffix: "महीने बचे",
    edit: "संपादित करें",
    delete: "हटाएँ",
    noGoalsYet: "अभी कोई बचत लक्ष्य नहीं है। ऊपर अपना पहला लक्ष्य बनाएं।",
    manualEntryPill: "मैनुअल एंट्री",
    manualEntryHero: "जब भी आपको तेज़ सुधार या नकद रिकॉर्ड चाहिए, खुद ट्रांजैक्शन जोड़ें।",
    manualEntryCopy: "नीचे ट्रांजैक्शन विवरण भरें। यदि आप तारीख या समय खाली छोड़ते हैं, तो SpendSmart वर्तमान सिस्टम तारीख और समय का उपयोग करेगा।",
    descriptionRequired: "विवरण आवश्यक है।",
    validAmountRequired: "मान्य राशि दर्ज करें।",
    addTransactionFailed: "ट्रांजैक्शन जोड़ा नहीं जा सका।",
    descriptionLabel: "विवरण",
    amountLabel: "राशि",
    typeLabel: "प्रकार",
    dateLabel: "तारीख",
    timeLabel: "समय",
    categoryLabel: "श्रेणी",
    descriptionPlaceholder: "बेकरी को भुगतान, वेतन जमा, नकद खरीद...",
    debit: "डेबिट",
    credit: "क्रेडिट",
    autoDetect: "स्वतः पहचान",
    addTransaction: "ट्रांजैक्शन जोड़ें",
    transactionAdded: "ट्रांजैक्शन सफलतापूर्वक जोड़ दिया गया",
    statementImport: "स्टेटमेंट इम्पोर्ट",
    selectPdfFirst: "पहले एक PDF बैंक स्टेटमेंट चुनें।",
    uploadFailed: "अपलोड विफल हुआ",
    exportFailed: "रिपोर्ट एक्सपोर्ट नहीं हो सकी",
    onlyPdfAccepted: "केवल PDF फाइलें स्वीकार की जाती हैं।",
    billOcrPill: "बिल OCR",
    selectBillFirst: "पहले एक बिल इमेज चुनें।",
    billUploadFailed: "बिल अपलोड विफल हुआ",
    imageFormatsHelp: "JPG, PNG और WEBP इमेज सबसे अच्छी तरह काम करती हैं।",
    appearance: "दिखावट",
    appearanceCopy: "यहीं से कभी भी लाइट और डार्क मोड के बीच बदलें।",
    uploadedFilesTitle: "PDFs",
    uploadedFilesCopy: "आपके अपलोड किए गए हर स्टेटमेंट और बिल को देखें, और जरूरत होने पर उनकी निकाली गई सारी जानकारी सहित हटाएँ।",
    uploadedFilesLoadFailed: "अपलोड की गई PDFs लोड नहीं हो सकीं।",
    uploadedFileDeleted: "अपलोड की गई फाइल और निकाला गया डेटा सफलतापूर्वक हट गया।",
    uploadedFileDeleteFailed: "अपलोड की गई फाइल हटाई नहीं जा सकी।",
    loadingUploadedFiles: "अपलोड की गई PDFs लोड हो रही हैं...",
    noUploadedFiles: "अभी कोई अपलोड की गई PDF या बिल नहीं है।",
    noCategoryData: "इस सीमा के लिए कोई श्रेणी डेटा उपलब्ध नहीं है।",
    categoryShareTitle: "श्रेणी हिस्सा",
    categoryShareSubtitle: "हर खर्च श्रेणी का प्रतिशत योगदान।",
    spendLegend: "खर्च",
    noTrendData: "इस सीमा के लिए कोई ट्रेंड डेटा उपलब्ध नहीं है।",
    trendOverviewTitle: "ट्रेंड अवलोकन",
    trendOverviewSubtitle: "समय के साथ खर्च और आय की चाल।",
    expenseSeries: "खर्च",
    incomeSeries: "आय",
    noComparisonData: "कोई तुलना डेटा उपलब्ध नहीं है।",
    comparisonSnapshotTitle: "तुलना स्नैपशॉट",
    comparisonSnapshotSubtitle: "चुने गए पीरियड के लिए त्वरित तुलना।",
    updated: "अपडेट हो गया",
    noUncategorizedTransactions: "अभी कोई अनकैटेगराइज़्ड ट्रांजैक्शन नहीं है।",
    uncategorizedTransactionsTitle: "अवर्गीकृत ट्रांजैक्शन",
    uncategorizedTransactionsHelp: "बाद में श्रेणी चुनें, और यह अपने-आप संबंधित रिपोर्ट में चला जाएगा।",
    select: "चुनें",
    viewMore: "और देखें",
    showRecent: "हाल के दिखाएं",
    loadMore: "और लोड करें",
    smartInsightsSummaryTitle: "स्मार्ट इनसाइट्स सारांश",
    smartInsightsSummaryFallback: "डेटा उपलब्ध नहीं है",
    assistantUnavailable: "अभी सहायक उपलब्ध नहीं है।",
    chatSuggestionsList: "रिपोर्ट्स, मासिक खर्च, मैंने अधिक क्यों खर्च किया, असामान्य ट्रांजैक्शन, बचत सुझाव।",
    categoryFood: "भोजन",
    categoryGroceries: "किराना",
    categoryTravel: "यात्रा",
    categoryShopping: "खरीदारी",
    categoryBills: "बिल",
    categoryEntertainment: "मनोरंजन",
    categoryEducation: "शिक्षा",
    categoryHealth: "स्वास्थ्य",
    categoryReimbursable: "वापस मिलने वाला",
    categoryIncome: "आय",
    categoryUncategorized: "अवर्गीकृत",
    healthExcellent: "उत्कृष्ट",
    healthHealthy: "स्वस्थ",
    healthNeedsAttention: "ध्यान चाहिए",
    healthAtRisk: "जोखिम में",
    healthNoData: "डेटा उपलब्ध नहीं है",
    documentPdf: "PDF",
    documentBill: "बिल",
    navProfile: "प्रोफ़ाइल",
    themeToggleLabel: "थीम बदलें",
    allCategories: "सभी श्रेणियाँ",
    showGoals: "लक्ष्य दिखाएं",
    hideGoals: "लक्ष्य छिपाएं",
    dashboardGoalsTitle: "लक्ष्य झलक",
    dashboardGoalsCopy: "डैशबोर्ड से ही अपने सक्रिय लक्ष्यों को ट्रैक करें।",
    daysRemaining: "दिन शेष",
    progress: "प्रगति",
    profileTitle: "प्रोफ़ाइल",
    profileSubtitle: "अपनी जानकारी, अपलोड और मैनुअल एंट्री देखें।",
    profileLoadingTitle: "प्रोफ़ाइल लोड हो रही है...",
    profileLoadingCopy: "खाता और फाइल इतिहास लाया जा रहा है।",
    profileLoadFailed: "प्रोफ़ाइल विवरण लोड नहीं हो पाया।",
    profilePdfsTitle: "PDFs",
    profilePdfsCopy: "आपके अपलोड किए गए बैंक स्टेटमेंट।",
    profileBillsTitle: "Bills",
    profileBillsCopy: "आपकी अपलोड की गई बिल/रसीद इमेज।",
    profileManualTitle: "मैनुअल ट्रांजैक्शन",
    profileManualCopy: "आपके द्वारा जोड़े गए मैनुअल ट्रांजैक्शन।",
    uploadedOn: "अपलोड तिथि",
    transactionRange: "ट्रांजैक्शन रेंज",
    showLess: "कम दिखाएं",
    noManualTransactions: "कोई मैनुअल ट्रांजैक्शन नहीं मिला।",
    manualEditTitle: "मैनुअल ट्रांजैक्शन संपादित करें",
    manualEditCopy: "केवल मैनुअल एंट्री संपादित की जा सकती है। PDF/BILL एंट्री read-only हैं।",
    manualLoadFailed: "मैनुअल ट्रांजैक्शन लोड नहीं हुए।",
    manualUpdated: "मैनुअल ट्रांजैक्शन सफलतापूर्वक अपडेट हुआ।",
    manualUpdateFailed: "मैनुअल ट्रांजैक्शन अपडेट नहीं हुआ।",
    editManualEntry: "मैनुअल एंट्री संपादित करें",
    saveChanges: "परिवर्तन सहेजें",
    manualTransactionDetails: "मैनुअल ट्रांजैक्शन विवरण",
    loading: "लोड हो रहा है...",
  },
  te: {
    navManual: "మాన్యువల్ ఎంట్రీ",
    navGoals: "లక్ష్యాలు",
    loginPill: "SpendSmart విశ్లేషణలు",
    loginThemeLight: "గ్రీన్ లైట్ థీమ్",
    loginThemeDark: "డీప్ గ్రీన్ నైట్ థీమ్",
    loginPanelCopy: "మీ ఆర్థిక డ్యాష్‌బోర్డ్, రిపోర్టులు, అప్లోడ్ టూల్స్ చూడడానికి లాగిన్ అవ్వండి.",
    loginFailed: "లాగిన్ విఫలమైంది",
    registerPill: "మీ వర్క్‌స్పేస్ సృష్టించండి",
    registerThemeLight: "ఫ్రెష్ గ్రీన్ మోడ్",
    registerThemeDark: "ఫారెస్ట్ డార్క్ మోడ్",
    registerPanelCopy: "ఒక్కసారి రిజిస్టర్ అయి, తర్వాత డ్యాష్‌బోర్డ్ మరియు రిపోర్ట్ సెంటర్‌ను ఉపయోగించండి.",
    registerSuccess: "విజయవంతంగా నమోదు అయ్యింది",
    registrationFailed: "నమోదు విఫలమైంది",
    dashboardLoadTitle: "డ్యాష్‌బోర్డ్ లోడ్ అవుతోంది...",
    dashboardLoadCopy: "మీ తాజా ఆర్థిక ట్రెండ్‌లు సిద్ధమవుతున్నాయి.",
    dashboardUnavailable: "డ్యాష్‌బోర్డ్ అందుబాటులో లేదు",
    financialCommandCenter: "ఆర్థిక కమాండ్ సెంటర్",
    financialHealthScore: "ఆర్థిక ఆరోగ్య స్కోర్",
    notEnoughData: "తగిన డేటా లేదు",
    whyThisScore: "ఈ స్కోర్ ఎందుకు?",
    savingsRatio: "సేవింగ్స్ నిష్పత్తి",
    overspendingFrequency: "అధిక ఖర్చు తరచుదనం",
    categoryBalanceScore: "కేటగిరీ సమతౌల్యం",
    noSpendingData: "ఖర్చు డేటా లేదు",
    dailyTrendTitle: "రోజువారీ ట్రెండ్",
    dailyTrendSubtitle: "ఎంచుకున్న తేదీ పరిధిలో రోజువారీ ఖర్చులు మరియు ఆదాయం.",
    weeklyViewTitle: "వారాంత వీక్షణం",
    weeklyViewSubtitle: "ప్యాటర్న్స్ త్వరగా గుర్తించడానికి వారాల వారీ కదలిక.",
    incomeExpenseSnapshotTitle: "ఆదాయం / ఖర్చు స్నాప్‌షాట్",
    incomeExpenseSnapshotSubtitle: "ప్రస్తుత పరిధిని గత పీరియడ్‌తో పోల్చండి.",
    reportsUnavailable: "రిపోర్టులు అందుబాటులో లేవు",
    financialReports: "ఆర్థిక రిపోర్టులు",
    reportsLoadingTitle: "రిపోర్టులు లోడ్ అవుతున్నాయి...",
    reportsLoadingCopy: "ట్రెండ్‌లు మరియు ఆర్థిక పోలికలు సిద్ధమవుతున్నాయి.",
    currentLabel: "ప్రస్తుత",
    previousLabel: "గత",
    changeLabel: "మార్పు",
    trendTitleSuffix: "ట్రెండ్",
    trendSelectedRangeSubtitle: "ఎంచుకున్న కస్టమ్ తేదీ పరిధికి ట్రెండ్ వివరాలు.",
    monthlySummaryTitle: "నెలవారీ సారాంశం",
    monthlySummarySubtitle: "ఎంచుకున్న పరిధిలో నెలవారీ అవలోకనం.",
    periodComparisonTitle: "కాలపరిమితి పోలిక",
    trendUp: "పెరిగింది",
    trendDown: "తగ్గింది",
    trendFlat: "స్థిరంగా ఉంది",
    totalExpensesShare: "మొత్తం ఖర్చులో",
    goalsHeroPill: "లక్ష్య ఆధారిత సేవింగ్స్ ప్లానర్",
    goalsHeroTitle: "భవిష్యత్ కొనుగోళ్లను స్పష్టమైన నెలవారీ సేవింగ్స్ ప్లాన్‌గా మార్చండి.",
    goalsHeroCopy: "ల్యాప్‌టాప్, బైక్, ప్రయాణం లేదా ఎమర్జెన్సీ ఫండ్ వంటి లక్ష్యాన్ని జోడించండి. SpendSmart మీ లక్ష్య మొత్తం, ఇప్పటివరకు సేవ్ చేసిన మొత్తం, చివరి తేదీ ఆధారంగా ప్రతి నెల ఎంత సేవ్ చేయాలో చెబుతుంది.",
    editGoalPlan: "లక్ష్య ప్లాన్ సవరించండి",
    createGoalPlan: "లక్ష్య ప్లాన్ సృష్టించండి",
    editGoalCopy: "మీరు పురోగతి సాధించినప్పుడల్లా సేవ్ చేసిన మొత్తం లేదా లక్ష్య వివరాలను నవీకరించండి.",
    createGoalCopy: "లక్ష్య మొత్తం, గడువు, ఇప్పటికే సేవ్ చేసిన మొత్తాన్ని సెట్ చేయండి.",
    cancelEdit: "సవరణ రద్దు చేయండి",
    goalTitlePlaceholder: "లక్ష్య శీర్షిక",
    targetAmountPlaceholder: "లక్ష్య మొత్తం",
    currentSavedPlaceholder: "ఇప్పటికే సేవ్ చేసినది",
    notesPlaceholder: "గమనికలు (ఐచ్చికం)",
    updateGoal: "లక్ష్యాన్ని నవీకరించండి",
    createPlan: "ప్లాన్ సృష్టించండి",
    goalUpdated: "లక్ష్యం విజయవంతంగా నవీకరించబడింది.",
    goalCreated: "లక్ష్య ప్లాన్ విజయవంతంగా సృష్టించబడింది.",
    goalsLoadFailed: "లక్ష్యాలు లోడ్ కాలేదు",
    goalUpdateFailed: "లక్ష్యాన్ని నవీకరించలేకపోయాము",
    goalCreateFailed: "లక్ష్యాన్ని సృష్టించలేకపోయాము",
    goalDeleteFailed: "లక్ష్యాన్ని తొలగించలేకపోయాము",
    savedGreaterThanTarget: "ఇప్పటికే సేవ్ చేసిన మొత్తం లక్ష్య మొత్తాన్ని మించకూడదు.",
    plannerPreview: "ప్లానర్ ప్రివ్యూ",
    remaining: "మిగిలింది",
    monthsLeft: "మిగిలిన నెలలు",
    savePerMonth: "నెలకు సేవ్ చేయాల్సింది",
    mySavingGoals: "నా సేవింగ్స్ లక్ష్యాలు",
    mySavingGoalsCopy: "మీ లక్ష్యాలను ట్రాక్ చేసి, సరైన మార్గంలో ఉండటానికి ప్రతి నెల ఎంత సేవ్ చేయాలో చూడండి.",
    loadingGoals: "మీ లక్ష్యాలు లోడ్ అవుతున్నాయి...",
    targetBy: "లక్ష్యం",
    saved: "సేవ్ చేసినది",
    complete: "పూర్తి",
    monthlyPlan: "నెలవారీ ప్లాన్",
    monthsLeftSuffix: "నెలలు మిగిలాయి",
    edit: "సవరించండి",
    delete: "తొలగించండి",
    noGoalsYet: "ఇంకా సేవింగ్స్ లక్ష్యాలు లేవు. పైన మీ మొదటి ప్లాన్ సృష్టించండి.",
    manualEntryPill: "మాన్యువల్ ఎంట్రీ",
    manualEntryHero: "త్వరిత సవరణ లేదా నగదు రికార్డు కోసం మీరు స్వయంగా ట్రాన్సాక్షన్ జోడించండి.",
    manualEntryCopy: "క్రింద ట్రాన్సాక్షన్ వివరాలు నమోదు చేయండి. తేదీ లేదా సమయం ఖాళీగా ఉంచితే SpendSmart ప్రస్తుత సిస్టమ్ తేదీ మరియు సమయాన్ని ఉపయోగిస్తుంది.",
    descriptionRequired: "వివరణ అవసరం.",
    validAmountRequired: "చెల్లుబాటు అయ్యే మొత్తాన్ని నమోదు చేయండి.",
    addTransactionFailed: "ట్రాన్సాక్షన్ జోడించలేకపోయాం.",
    descriptionLabel: "వివరణ",
    amountLabel: "మొత్తం",
    typeLabel: "రకం",
    dateLabel: "తేదీ",
    timeLabel: "సమయం",
    categoryLabel: "వర్గం",
    descriptionPlaceholder: "బేకరీకి చెల్లింపు, జీతం జమ, నగదు కొనుగోలు...",
    debit: "డెబిట్",
    credit: "క్రెడిట్",
    autoDetect: "స్వయంచాలక గుర్తింపు",
    addTransaction: "ట్రాన్సాక్షన్ జోడించండి",
    transactionAdded: "ట్రాన్సాక్షన్ విజయవంతంగా జోడించబడింది",
    statementImport: "స్టేట్‌మెంట్ దిగుమతి",
    selectPdfFirst: "ముందుగా ఒక PDF బ్యాంక్ స్టేట్‌మెంట్ ఎంచుకోండి.",
    uploadFailed: "అప్లోడ్ విఫలమైంది",
    exportFailed: "రిపోర్ట్ ఎగుమతి చేయలేకపోయాము",
    onlyPdfAccepted: "కేవలం PDF ఫైళ్లు మాత్రమే అనుమతించబడతాయి.",
    billOcrPill: "బిల్ OCR",
    selectBillFirst: "ముందుగా ఒక బిల్ ఇమేజ్ ఎంచుకోండి.",
    billUploadFailed: "బిల్ అప్లోడ్ విఫలమైంది",
    imageFormatsHelp: "JPG, PNG, WEBP చిత్రాలు ఉత్తమంగా పనిచేస్తాయి.",
    appearance: "రూపం",
    appearanceCopy: "ఇక్కడి నుంచే లైట్ మరియు డార్క్ మోడ్‌ల మధ్య ఎప్పుడైనా మార్చుకోండి.",
    uploadedFilesTitle: "PDFలు",
    uploadedFilesCopy: "మీరు అప్లోడ్ చేసిన ప్రతి స్టేట్‌మెంట్ మరియు బిల్‌ను చూడండి, అవసరమైతే వాటి నుంచి తీసిన మొత్తం డేటాతో పాటు తొలగించండి.",
    uploadedFilesLoadFailed: "అప్లోడ్ చేసిన PDFలను లోడ్ చేయలేకపోయాము.",
    uploadedFileDeleted: "అప్లోడ్ చేసిన ఫైల్ మరియు దాని డేటా విజయవంతంగా తొలగించబడింది.",
    uploadedFileDeleteFailed: "అప్లోడ్ చేసిన ఫైల్‌ను తొలగించలేకపోయాము.",
    loadingUploadedFiles: "అప్లోడ్ చేసిన PDFలు లోడ్ అవుతున్నాయి...",
    noUploadedFiles: "ఇంకా అప్లోడ్ చేసిన PDFలు లేదా బిల్లులు లేవు.",
    noCategoryData: "ఈ పరిధికి కేటగిరీ డేటా లేదు.",
    categoryShareTitle: "కేటగిరీ వాటా",
    categoryShareSubtitle: "ప్రతి ఖర్చు కేటగిరీ యొక్క శాతం వాటా.",
    spendLegend: "ఖర్చు",
    noTrendData: "ఈ పరిధికి ట్రెండ్ డేటా లేదు.",
    trendOverviewTitle: "ట్రెండ్ అవలోకనం",
    trendOverviewSubtitle: "కాలక్రమంలో ఖర్చు మరియు ఆదాయం కదలిక.",
    expenseSeries: "ఖర్చు",
    incomeSeries: "ఆదాయం",
    noComparisonData: "పోలిక డేటా అందుబాటులో లేదు.",
    comparisonSnapshotTitle: "పోలిక స్నాప్‌షాట్",
    comparisonSnapshotSubtitle: "ఎంచుకున్న కాలానికి త్వరిత పోలిక.",
    updated: "నవీకరించబడింది",
    noUncategorizedTransactions: "ప్రస్తుతం వర్గీకరించని ట్రాన్సాక్షన్లు లేవు.",
    uncategorizedTransactionsTitle: "వర్గీకరించని ట్రాన్సాక్షన్లు",
    uncategorizedTransactionsHelp: "తరువాత వర్గం ఎంచుకోండి, అది స్వయంచాలితంగా సంబంధిత రిపోర్ట్‌లోకి వెళ్తుంది.",
    select: "ఎంచుకోండి",
    viewMore: "ఇంకా చూడండి",
    showRecent: "ఇటీవలివి చూపించు",
    loadMore: "మరిన్ని లోడ్ చేయండి",
    smartInsightsSummaryTitle: "స్మార్ట్ ఇన్‌సైట్స్ సారాంశం",
    smartInsightsSummaryFallback: "డేటా అందుబాటులో లేదు",
    assistantUnavailable: "ప్రస్తుతం సహాయకుడు అందుబాటులో లేడు.",
    chatSuggestionsList: "రిపోర్టులు, నెలవారీ ఖర్చులు, నేను ఎక్కువ ఎందుకు ఖర్చు చేశాను, అసాధారణ ట్రాన్సాక్షన్లు, సేవింగ్స్ సూచనలు.",
    categoryFood: "ఆహారం",
    categoryGroceries: "కిరాణా",
    categoryTravel: "ప్రయాణం",
    categoryShopping: "షాపింగ్",
    categoryBills: "బిల్లులు",
    categoryEntertainment: "వినోదం",
    categoryEducation: "విద్య",
    categoryHealth: "ఆరోగ్యం",
    categoryReimbursable: "తిరిగి పొందదగినది",
    categoryIncome: "ఆదాయం",
    categoryUncategorized: "వర్గీకరించని",
    healthExcellent: "అద్భుతం",
    healthHealthy: "ఆరోగ్యకరం",
    healthNeedsAttention: "శ్రద్ధ అవసరం",
    healthAtRisk: "ప్రమాదంలో",
    healthNoData: "డేటా అందుబాటులో లేదు",
    documentPdf: "PDF",
    documentBill: "బిల్",
    navProfile: "ప్రొఫైల్",
    themeToggleLabel: "థీమ్ మార్చు",
    allCategories: "అన్ని వర్గాలు",
    showGoals: "లక్ష్యాలు చూపించు",
    hideGoals: "లక్ష్యాలు దాచు",
    dashboardGoalsTitle: "లక్ష్యాల సారాంశం",
    dashboardGoalsCopy: "డ్యాష్‌బోర్డ్ నుంచే మీ లక్ష్యాల ప్రగతిని చూసుకోండి.",
    daysRemaining: "రోజులు మిగిలినవి",
    progress: "ప్రగతి",
    profileTitle: "ప్రొఫైల్",
    profileSubtitle: "మీ ఖాతా వివరాలు, అప్లోడ్‌లు, మాన్యువల్ లావాదేవీలు చూడండి.",
    profileLoadingTitle: "ప్రొఫైల్ లోడ్ అవుతోంది...",
    profileLoadingCopy: "ఖాతా మరియు ఫైల్ చరిత్రను లోడ్ చేస్తున్నాం.",
    profileLoadFailed: "ప్రొఫైల్ వివరాలు లోడ్ కాలేదు.",
    profilePdfsTitle: "PDFలు",
    profilePdfsCopy: "మీరు అప్లోడ్ చేసిన బ్యాంక్ స్టేట్మెంట్‌లు.",
    profileBillsTitle: "బిల్లులు",
    profileBillsCopy: "మీరు అప్లోడ్ చేసిన బిల్/రిసీట్ చిత్రాలు.",
    profileManualTitle: "మాన్యువల్ లావాదేవీలు",
    profileManualCopy: "మీరు చేతితో జోడించిన లావాదేవీలు.",
    uploadedOn: "అప్లోడ్ తేది",
    transactionRange: "లావాదేవీ పరిధి",
    showLess: "తక్కువ చూపించు",
    noManualTransactions: "మాన్యువల్ లావాదేవీలు లేవు.",
    manualEditTitle: "మాన్యువల్ లావాదేవీలు సవరించు",
    manualEditCopy: "మాన్యువల్ ఎంట్రీలనే సవరించవచ్చు. PDF/BILL ఎంట్రీలు read-only.",
    manualLoadFailed: "మాన్యువల్ లావాదేవీలు లోడ్ కాలేదు.",
    manualUpdated: "మాన్యువల్ లావాదేవీ విజయవంతంగా నవీకరించబడింది.",
    manualUpdateFailed: "మాన్యువల్ లావాదేవీ నవీకరణ విఫలమైంది.",
    editManualEntry: "మాన్యువల్ ఎంట్రీ సవరించు",
    saveChanges: "మార్పులు సేవ్ చేయండి",
    manualTransactionDetails: "మాన్యువల్ లావాదేవీ వివరాలు",
    loading: "లోడ్ అవుతోంది...",
  },
  kn: {
    navManual: "ಕೈಯಾರೆ ನಮೂದು",
    navGoals: "ಗುರಿಗಳು",
    loginPill: "SpendSmart ವಿಶ್ಲೇಷಣೆಗಳು",
    loginThemeLight: "ಹಸಿರು ಲೈಟ್ ಥೀಮ್",
    loginThemeDark: "ಡೀಪ್ ಗ್ರೀನ್ ನೈಟ್ ಥೀಮ್",
    loginPanelCopy: "ನಿಮ್ಮ ಹಣಕಾಸು ಡ್ಯಾಶ್‌ಬೋರ್ಡ್, ವರದಿಗಳು ಮತ್ತು ಅಪ್‌ಲೋಡ್ ಸಾಧನಗಳನ್ನು ನೋಡಲು ಲಾಗಿನ್ ಮಾಡಿ.",
    loginFailed: "ಲಾಗಿನ್ ವಿಫಲವಾಗಿದೆ",
    registerPill: "ನಿಮ್ಮ ವರ್ಕ್‌ಸ್ಪೇಸ್ ರಚಿಸಿ",
    registerThemeLight: "ಫ್ರೆಶ್ ಗ್ರೀನ್ ಮೋಡ್",
    registerThemeDark: "ಫಾರೆಸ್ಟ್ ಡಾರ್ಕ್ ಮೋಡ್",
    registerPanelCopy: "ಒಮ್ಮೆ ನೋಂದಾಯಿಸಿ, ನಂತರ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್ ಮತ್ತು ವರದಿ ಕೇಂದ್ರವನ್ನು ಪ್ರವೇಶಿಸಿ.",
    registerSuccess: "ಯಶಸ್ವಿಯಾಗಿ ನೋಂದಾಯಿಸಲಾಗಿದೆ",
    registrationFailed: "ನೋಂದಣಿ ವಿಫಲವಾಗಿದೆ",
    dashboardLoadTitle: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್ ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
    dashboardLoadCopy: "ನಿಮ್ಮ ಇತ್ತೀಚಿನ ಹಣಕಾಸು ಟ್ರೆಂಡ್‌ಗಳನ್ನು ಸಿದ್ಧಪಡಿಸಲಾಗುತ್ತಿದೆ.",
    dashboardUnavailable: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್ ಲಭ್ಯವಿಲ್ಲ",
    financialCommandCenter: "ಹಣಕಾಸು ಕಮಾಂಡ್ ಸೆಂಟರ್",
    financialHealthScore: "ಹಣಕಾಸು ಆರೋಗ್ಯ ಅಂಕೆ",
    notEnoughData: "ಸಾಕಷ್ಟು ಡೇಟಾ ಇಲ್ಲ",
    whyThisScore: "ಈ ಅಂಕೆ ಯಾಕೆ?",
    savingsRatio: "ಉಳಿತಾಯ ಅನುಪಾತ",
    overspendingFrequency: "ಅತಿಖರ್ಚಿನ ಆವೃತ್ತಿ",
    categoryBalanceScore: "ವರ್ಗ ಸಮತೋಲನ",
    noSpendingData: "ಖರ್ಚಿನ ಡೇಟಾ ಇಲ್ಲ",
    dailyTrendTitle: "ದೈನಂದಿನ ಟ್ರೆಂಡ್",
    dailyTrendSubtitle: "ಆಯ್ದ ದಿನಾಂಕ ವ್ಯಾಪ್ತಿಯ ದೈನಂದಿನ ಖರ್ಚು ಮತ್ತು ಆದಾಯ.",
    weeklyViewTitle: "ವಾರದ ನೋಟ",
    weeklyViewSubtitle: "ಪ್ಯಾಟರ್ನ್ ಗುರುತಿಸಲು ವಾರವಾರ ಗುಂಪುಗೊಳಿಸಿದ ಚಲನೆ.",
    incomeExpenseSnapshotTitle: "ಆದಾಯ / ಖರ್ಚು ಸ್ನ್ಯಾಪ್‌ಶಾಟ್",
    incomeExpenseSnapshotSubtitle: "ಪ್ರಸ್ತುತ ವ್ಯಾಪ್ತಿಯನ್ನು ಹಿಂದಿನ ಅವಧಿಯೊಂದಿಗೆ ಹೋಲಿಸಿ.",
    reportsUnavailable: "ವರದಿಗಳು ಲಭ್ಯವಿಲ್ಲ",
    financialReports: "ಹಣಕಾಸು ವರದಿಗಳು",
    reportsLoadingTitle: "ವರದಿಗಳು ಲೋಡ್ ಆಗುತ್ತಿವೆ...",
    reportsLoadingCopy: "ಟ್ರೆಂಡ್‌ಗಳು ಮತ್ತು ಹಣಕಾಸು ಹೋಲಿಕೆಗಳು ಸಿದ್ಧವಾಗುತ್ತಿವೆ.",
    currentLabel: "ಪ್ರಸ್ತುತ",
    previousLabel: "ಹಿಂದಿನ",
    changeLabel: "ಬದಲಾವಣೆ",
    trendTitleSuffix: "ಟ್ರೆಂಡ್",
    trendSelectedRangeSubtitle: "ಆಯ್ದ ಕಸ್ಟಮ್ ದಿನಾಂಕ ವ್ಯಾಪ್ತಿಗೆ ಟ್ರೆಂಡ್ ವಿವರ.",
    monthlySummaryTitle: "ಮಾಸಿಕ ಸಾರಾಂಶ",
    monthlySummarySubtitle: "ಆಯ್ದ ವ್ಯಾಪ್ತಿಯೊಳಗಿನ ತಿಂಗಳವಾರು ಅವಲೋಕನ.",
    periodComparisonTitle: "ಅವಧಿ ಹೋಲಿಕೆ",
    trendUp: "ಹೆಚ್ಚು",
    trendDown: "ಕಡಿಮೆ",
    trendFlat: "ಸ್ಥಿರ",
    totalExpensesShare: "ಒಟ್ಟು ಖರ್ಚಿನ",
    goalsHeroPill: "ಗುರಿ ಆಧಾರಿತ ಉಳಿತಾಯ ಯೋಜಕ",
    goalsHeroTitle: "ಭವಿಷ್ಯದ ಖರೀದಿಗಳನ್ನು ಸ್ಪಷ್ಟ ಮಾಸಿಕ ಉಳಿತಾಯ ಯೋಜನೆಯಾಗಿ ಮಾಡಿ.",
    goalsHeroCopy: "ಲ್ಯಾಪ್‌ಟಾಪ್, ಬೈಕ್, ಪ್ರವಾಸ ಅಥವಾ ತುರ್ತು ನಿಧಿ ಮುಂತಾದ ಗುರಿಯನ್ನು ಸೇರಿಸಿ. SpendSmart ನಿಮ್ಮ ಗುರಿ ಮೊತ್ತ, ಈಗಾಗಲೇ ಉಳಿಸಿದ ಮೊತ್ತ ಮತ್ತು ಅಂತಿಮ ದಿನಾಂಕದ ಆಧಾರದಲ್ಲಿ ಪ್ರತಿ ತಿಂಗಳು ಎಷ್ಟು ಉಳಿಸಬೇಕು ಎಂದು ಲೆಕ್ಕ ಹಾಕುತ್ತದೆ.",
    editGoalPlan: "ಗುರಿ ಯೋಜನೆ ಸಂಪಾದಿಸಿ",
    createGoalPlan: "ಗುರಿ ಯೋಜನೆ ರಚಿಸಿ",
    editGoalCopy: "ನೀವು ಪ್ರಗತಿ ಸಾಧಿಸಿದಾಗ ಉಳಿಸಿದ ಮೊತ್ತ ಅಥವಾ ಗುರಿ ವಿವರಗಳನ್ನು ನವೀಕರಿಸಿ.",
    createGoalCopy: "ಗುರಿ ಮೊತ್ತ, ಗಡುವು ಮತ್ತು ಈಗಾಗಲೇ ಉಳಿಸಿದ ಮೊತ್ತವನ್ನು ನಿಗದಿಪಡಿ.",
    cancelEdit: "ಸಂಪಾದನೆ ರದ್ದುಮಾಡಿ",
    goalTitlePlaceholder: "ಗುರಿ ಶೀರ್ಷಿಕೆ",
    targetAmountPlaceholder: "ಗುರಿ ಮೊತ್ತ",
    currentSavedPlaceholder: "ಈಗಾಗಲೇ ಉಳಿಸಿದದ್ದು",
    notesPlaceholder: "ಟಿಪ್ಪಣಿಗಳು (ಐಚ್ಛಿಕ)",
    updateGoal: "ಗುರಿ ನವೀಕರಿಸಿ",
    createPlan: "ಯೋಜನೆ ರಚಿಸಿ",
    goalUpdated: "ಗುರಿ ಯಶಸ್ವಿಯಾಗಿ ನವೀಕರಿಸಲಾಗಿದೆ.",
    goalCreated: "ಗುರಿ ಯೋಜನೆ ಯಶಸ್ವಿಯಾಗಿ ರಚಿಸಲಾಗಿದೆ.",
    goalsLoadFailed: "ಗುರಿಗಳನ್ನು ಲೋಡ್ ಮಾಡಲು ವಿಫಲವಾಗಿದೆ",
    goalUpdateFailed: "ಗುರಿ ನವೀಕರಿಸಲು ವಿಫಲವಾಗಿದೆ",
    goalCreateFailed: "ಗುರಿ ರಚಿಸಲು ವಿಫಲವಾಗಿದೆ",
    goalDeleteFailed: "ಗುರಿ ಅಳಿಸಲು ವಿಫಲವಾಗಿದೆ",
    savedGreaterThanTarget: "ಈಗಾಗಲೇ ಉಳಿಸಿದ ಮೊತ್ತ ಗುರಿ ಮೊತ್ತಕ್ಕಿಂತ ಹೆಚ್ಚಿರಬಾರದು.",
    plannerPreview: "ಯೋಜನೆ ಪೂರ್ವದೃಶ್ಯ",
    remaining: "ಉಳಿದದ್ದು",
    monthsLeft: "ಉಳಿದ ತಿಂಗಳುಗಳು",
    savePerMonth: "ತಿಂಗಳಿಗೆ ಉಳಿಸಬೇಕಾದದ್ದು",
    mySavingGoals: "ನನ್ನ ಉಳಿತಾಯ ಗುರಿಗಳು",
    mySavingGoalsCopy: "ನಿಮ್ಮ ಗುರಿಗಳನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ ಮತ್ತು ಸರಿಯಾದ ದಾರಿಯಲ್ಲಿ ಇರಲು ಪ್ರತಿ ತಿಂಗಳು ಎಷ್ಟು ಉಳಿಸಬೇಕು ನೋಡಿ.",
    loadingGoals: "ನಿಮ್ಮ ಗುರಿಗಳು ಲೋಡ್ ಆಗುತ್ತಿವೆ...",
    targetBy: "ಗುರಿ",
    saved: "ಉಳಿಸಿದದ್ದು",
    complete: "ಪೂರ್ಣ",
    monthlyPlan: "ಮಾಸಿಕ ಯೋಜನೆ",
    monthsLeftSuffix: "ತಿಂಗಳುಗಳು ಉಳಿದಿವೆ",
    edit: "ಸಂಪಾದಿಸಿ",
    delete: "ಅಳಿಸಿ",
    noGoalsYet: "ಇನ್ನೂ ಯಾವುದೇ ಉಳಿತಾಯ ಗುರಿಗಳಿಲ್ಲ. ಮೇಲಿಂದ ನಿಮ್ಮ ಮೊದಲ ಯೋಜನೆಯನ್ನು ರಚಿಸಿ.",
    manualEntryPill: "ಕೈಯಾರೆ ನಮೂದು",
    manualEntryHero: "ವೇಗವಾದ ತಿದ್ದುಪಡಿ ಅಥವಾ ನಗದು ದಾಖಲೆ ಬೇಕಾದಾಗ ಸ್ವತಃ ವ್ಯವಹಾರವನ್ನು ಸೇರಿಸಿ.",
    manualEntryCopy: "ಕೆಳಗೆ ವ್ಯವಹಾರದ ವಿವರಗಳನ್ನು ನಮೂದಿಸಿ. ದಿನಾಂಕ ಅಥವಾ ಸಮಯವನ್ನು ಖಾಲಿ ಬಿಡಿದರೆ SpendSmart ಪ್ರಸ್ತುತ ವ್ಯವಸ್ಥೆಯ ದಿನಾಂಕ ಮತ್ತು ಸಮಯವನ್ನು ಬಳಸುತ್ತದೆ.",
    descriptionRequired: "ವಿವರಣೆ ಅಗತ್ಯವಿದೆ.",
    validAmountRequired: "ಮಾನ್ಯ ಮೊತ್ತವನ್ನು ನಮೂದಿಸಿ.",
    addTransactionFailed: "ವ್ಯವಹಾರವನ್ನು ಸೇರಿಸಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ.",
    descriptionLabel: "ವಿವರಣೆ",
    amountLabel: "ಮೊತ್ತ",
    typeLabel: "ಪ್ರಕಾರ",
    dateLabel: "ದಿನಾಂಕ",
    timeLabel: "ಸಮಯ",
    categoryLabel: "ವರ್ಗ",
    descriptionPlaceholder: "ಬೇಕರಿಗೆ ಪಾವತಿ, ವೇತನ ಜಮಾ, ನಗದು ಖರೀದಿ...",
    debit: "ಡೆಬಿಟ್",
    credit: "ಕ್ರೆಡಿಟ್",
    autoDetect: "ಸ್ವಯಂ ಗುರುತು",
    addTransaction: "ವ್ಯವಹಾರ ಸೇರಿಸಿ",
    transactionAdded: "ವ್ಯವಹಾರ ಯಶಸ್ವಿಯಾಗಿ ಸೇರಿಸಲಾಗಿದೆ",
    statementImport: "ಸ್ಟೇಟ್ಮೆಂಟ್ ಇಂಪೋರ್ಟ್",
    selectPdfFirst: "ಮೊದಲು ಒಂದು PDF ಬ್ಯಾಂಕ್ ಸ್ಟೇಟ್ಮೆಂಟ್ ಆಯ್ಕೆಮಾಡಿ.",
    uploadFailed: "ಅಪ್‌ಲೋಡ್ ವಿಫಲವಾಗಿದೆ",
    exportFailed: "ವರದಿಯನ್ನು ಎಕ್ಸ್‌ಪೋರ್ಟ್ ಮಾಡಲು ವಿಫಲವಾಗಿದೆ",
    onlyPdfAccepted: "PDF ಫೈಲ್‌ಗಳನ್ನು ಮಾತ್ರ ಅನುಮತಿಸಲಾಗಿದೆ.",
    billOcrPill: "ಬಿಲ್ OCR",
    selectBillFirst: "ಮೊದಲು ಒಂದು ಬಿಲ್ ಚಿತ್ರವನ್ನು ಆಯ್ಕೆಮಾಡಿ.",
    billUploadFailed: "ಬಿಲ್ ಅಪ್‌ಲೋಡ್ ವಿಫಲವಾಗಿದೆ",
    imageFormatsHelp: "JPG, PNG ಮತ್ತು WEBP ಚಿತ್ರಗಳು ಉತ್ತಮವಾಗಿ ಕೆಲಸ ಮಾಡುತ್ತವೆ.",
    appearance: "ದೃಶ್ಯ ರೂಪ",
    appearanceCopy: "ಇಲ್ಲಿಂದಲೇ ಯಾವಾಗ ಬೇಕಾದರೂ ಲೈಟ್ ಮತ್ತು ಡಾರ್ಕ್ ಮೋಡ್ ನಡುವೆ ಬದಲಾಯಿಸಿ.",
    uploadedFilesTitle: "PDFಗಳು",
    uploadedFilesCopy: "ನೀವು ಅಪ್‌ಲೋಡ್ ಮಾಡಿದ ಪ್ರತಿಯೊಂದು ಸ್ಟೇಟ್ಮೆಂಟ್ ಮತ್ತು ಬಿಲ್ ಅನ್ನು ನೋಡಿ, ಅಗತ್ಯವಿದ್ದರೆ ಅವುಗಳ ಎಲ್ಲಾ ಡೇಟಾ ಸಹಿತ ಅಳಿಸಿ.",
    uploadedFilesLoadFailed: "ಅಪ್‌ಲೋಡ್ ಮಾಡಿದ PDFಗಳನ್ನು ಲೋಡ್ ಮಾಡಲು ವಿಫಲವಾಗಿದೆ.",
    uploadedFileDeleted: "ಅಪ್‌ಲೋಡ್ ಮಾಡಿದ ಫೈಲ್ ಮತ್ತು ಅದರ ಡೇಟಾ ಯಶಸ್ವಿಯಾಗಿ ಅಳಿಸಲಾಗಿದೆ.",
    uploadedFileDeleteFailed: "ಅಪ್‌ಲೋಡ್ ಮಾಡಿದ ಫೈಲ್ ಅಳಿಸಲು ವಿಫಲವಾಗಿದೆ.",
    loadingUploadedFiles: "ಅಪ್‌ಲೋಡ್ ಮಾಡಿದ PDFಗಳು ಲೋಡ್ ಆಗುತ್ತಿವೆ...",
    noUploadedFiles: "ಇನ್ನೂ ಯಾವುದೇ ಅಪ್‌ಲೋಡ್ ಮಾಡಿದ PDFಗಳು ಅಥವಾ ಬಿಲ್ಲುಗಳು ಇಲ್ಲ.",
    noCategoryData: "ಈ ವ್ಯಾಪ್ತಿಗೆ ವರ್ಗ ಡೇಟಾ ಲಭ್ಯವಿಲ್ಲ.",
    categoryShareTitle: "ವರ್ಗ ಹಂಚಿಕೆ",
    categoryShareSubtitle: "ಪ್ರತಿ ಖರ್ಚು ವರ್ಗದ ಶೇಕಡಾವಾರು ಕೊಡುಗೆ.",
    spendLegend: "ಖರ್ಚು",
    noTrendData: "ಈ ವ್ಯಾಪ್ತಿಗೆ ಟ್ರೆಂಡ್ ಡೇಟಾ ಲಭ್ಯವಿಲ್ಲ.",
    trendOverviewTitle: "ಟ್ರೆಂಡ್ ಅವಲೋಕನ",
    trendOverviewSubtitle: "ಕಾಲಕ್ರಮದಲ್ಲಿ ಖರ್ಚು ಮತ್ತು ಆದಾಯ ಚಲನೆ.",
    expenseSeries: "ಖರ್ಚು",
    incomeSeries: "ಆದಾಯ",
    noComparisonData: "ಹೋಲಿಕೆ ಡೇಟಾ ಲಭ್ಯವಿಲ್ಲ.",
    comparisonSnapshotTitle: "ಹೋಲಿಕೆ ಸ್ನ್ಯಾಪ್‌ಶಾಟ್",
    comparisonSnapshotSubtitle: "ಆಯ್ದ ಅವಧಿಗೆ ವೇಗವಾದ ಹೋಲಿಕೆ.",
    updated: "ನವೀಕರಿಸಲಾಗಿದೆ",
    noUncategorizedTransactions: "ಈಗ ಯಾವುದೇ ವರ್ಗೀಕರಿಸದ ವ್ಯವಹಾರಗಳಿಲ್ಲ.",
    uncategorizedTransactionsTitle: "ವರ್ಗೀಕರಿಸದ ವ್ಯವಹಾರಗಳು",
    uncategorizedTransactionsHelp: "ನಂತರ ವರ್ಗವನ್ನು ಆಯ್ಕೆ ಮಾಡಿ; ಅದು ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಸಂಬಂಧಿತ ವರದಿಗೆ ಸಾಗುತ್ತದೆ.",
    select: "ಆಯ್ಕೆಮಾಡಿ",
    viewMore: "ಇನ್ನಷ್ಟು ನೋಡಿ",
    showRecent: "ಇತ್ತೀಚಿನವು ತೋರಿಸಿ",
    loadMore: "ಇನ್ನಷ್ಟು ಲೋಡ್ ಮಾಡಿ",
    smartInsightsSummaryTitle: "ಸ್ಮಾರ್ಟ್ ಒಳನೋಟಗಳ ಸಾರಾಂಶ",
    smartInsightsSummaryFallback: "ಡೇಟಾ ಲಭ್ಯವಿಲ್ಲ",
    assistantUnavailable: "ಸಹಾಯಕ ಈಗ ಲಭ್ಯವಿಲ್ಲ.",
    chatSuggestionsList: "ವರದಿಗಳು, ಮಾಸಿಕ ಖರ್ಚುಗಳು, ನಾನು ಹೆಚ್ಚು ಏಕೆ ಖರ್ಚು ಮಾಡಿದೆ, ಅಸಾಮಾನ್ಯ ವ್ಯವಹಾರಗಳು, ಉಳಿತಾಯ ಸಲಹೆಗಳು.",
    categoryFood: "ಆಹಾರ",
    categoryGroceries: "ಕಿರಾಣಿ",
    categoryTravel: "ಪ್ರಯಾಣ",
    categoryShopping: "ಖರೀದಿ",
    categoryBills: "ಬಿಲ್ಲುಗಳು",
    categoryEntertainment: "ಮನರಂಜನೆ",
    categoryEducation: "ಶಿಕ್ಷಣ",
    categoryHealth: "ಆರೋಗ್ಯ",
    categoryReimbursable: "ಮರುಪಾವತಿ",
    categoryIncome: "ಆದಾಯ",
    categoryUncategorized: "ವರ್ಗೀಕರಿಸದ",
    healthExcellent: "ಅತ್ಯುತ್ತಮ",
    healthHealthy: "ಆರೋಗ್ಯಕರ",
    healthNeedsAttention: "ಗಮನ ಅಗತ್ಯ",
    healthAtRisk: "ಅಪಾಯದಲ್ಲಿದೆ",
    healthNoData: "ಡೇಟಾ ಲಭ್ಯವಿಲ್ಲ",
    documentPdf: "PDF",
    documentBill: "ಬಿಲ್",
    navProfile: "ಪ್ರೊಫೈಲ್",
    themeToggleLabel: "ಥೀಮ್ ಬದಲಿಸಿ",
    allCategories: "ಎಲ್ಲ ವರ್ಗಗಳು",
    showGoals: "ಗುರಿಗಳನ್ನು ತೋರಿಸಿ",
    hideGoals: "ಗುರಿಗಳನ್ನು ಮರೆಮಾಡಿ",
    dashboardGoalsTitle: "ಗುರಿಗಳ ಸಾರಾಂಶ",
    dashboardGoalsCopy: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ನಲ್ಲೇ ನಿಮ್ಮ ಗುರಿ ಪ್ರಗತಿಯನ್ನು ನೋಡಿ.",
    daysRemaining: "ಉಳಿದ ದಿನಗಳು",
    progress: "ಪ್ರಗತಿ",
    profileTitle: "ಪ್ರೊಫೈಲ್",
    profileSubtitle: "ನಿಮ್ಮ ಖಾತೆ ವಿವರಗಳು, ಅಪ್‌ಲೋಡ್‌ಗಳು ಮತ್ತು ಕೈಯಾರೆ ವ್ಯವಹಾರಗಳನ್ನು ನೋಡಿ.",
    profileLoadingTitle: "ಪ್ರೊಫೈಲ್ ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
    profileLoadingCopy: "ಖಾತೆ ಮತ್ತು ಫೈಲ್ ಇತಿಹಾಸವನ್ನು ಪಡೆಯಲಾಗುತ್ತಿದೆ.",
    profileLoadFailed: "ಪ್ರೊಫೈಲ್ ವಿವರಗಳನ್ನು ಲೋಡ್ ಮಾಡಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ.",
    profilePdfsTitle: "PDFಗಳು",
    profilePdfsCopy: "ನೀವು ಅಪ್‌ಲೋಡ್ ಮಾಡಿದ ಬ್ಯಾಂಕ್ ಸ್ಟೇಟ್‌ಮೆಂಟ್‌ಗಳು.",
    profileBillsTitle: "ಬಿಲ್ಲುಗಳು",
    profileBillsCopy: "ನೀವು ಅಪ್‌ಲೋಡ್ ಮಾಡಿದ ಬಿಲ್/ರಸೀದಿ ಚಿತ್ರಗಳು.",
    profileManualTitle: "ಕೈಯಾರೆ ವ್ಯವಹಾರಗಳು",
    profileManualCopy: "ನೀವು ಕೈಯಾರೆ ಸೇರಿಸಿದ ವ್ಯವಹಾರಗಳು.",
    uploadedOn: "ಅಪ್‌ಲೋಡ್ ದಿನಾಂಕ",
    transactionRange: "ವ್ಯವಹಾರ ಅವಧಿ",
    showLess: "ಕಡಿಮೆ ತೋರಿಸಿ",
    noManualTransactions: "ಯಾವುದೇ ಕೈಯಾರೆ ವ್ಯವಹಾರಗಳಿಲ್ಲ.",
    manualEditTitle: "ಕೈಯಾರೆ ವ್ಯವಹಾರಗಳನ್ನು ಸಂಪಾದಿಸಿ",
    manualEditCopy: "ಕೇವಲ ಕೈಯಾರೆ ಎಂಟ್ರಿಗಳನ್ನು ಮಾತ್ರ ಸಂಪಾದಿಸಬಹುದು. PDF/BILL ಎಂಟ್ರಿಗಳು read-only.",
    manualLoadFailed: "ಕೈಯಾರೆ ವ್ಯವಹಾರಗಳನ್ನು ಲೋಡ್ ಮಾಡಲು ಆಗಲಿಲ್ಲ.",
    manualUpdated: "ಕೈಯಾರೆ ವ್ಯವಹಾರ ಯಶಸ್ವಿಯಾಗಿ ನವೀಕರಿಸಲಾಗಿದೆ.",
    manualUpdateFailed: "ಕೈಯಾರೆ ವ್ಯವಹಾರ ನವೀಕರಣ ವಿಫಲವಾಗಿದೆ.",
    editManualEntry: "ಕೈಯಾರೆ ಎಂಟ್ರಿ ಸಂಪಾದಿಸಿ",
    saveChanges: "ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಿ",
    manualTransactionDetails: "ಕೈಯಾರೆ ವ್ಯವಹಾರ ವಿವರಗಳು",
    loading: "ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
  },
};

const categoryTranslationKeys = {
  Food: "categoryFood",
  Groceries: "categoryGroceries",
  Travel: "categoryTravel",
  Shopping: "categoryShopping",
  Bills: "categoryBills",
  Entertainment: "categoryEntertainment",
  Education: "categoryEducation",
  Health: "categoryHealth",
  Reimbursable: "categoryReimbursable",
  Income: "categoryIncome",
  Uncategorized: "categoryUncategorized",
};

const healthTranslationKeys = {
  Excellent: "healthExcellent",
  Healthy: "healthHealthy",
  "Needs Attention": "healthNeedsAttention",
  "At Risk": "healthAtRisk",
  "No data available": "healthNoData",
};

const documentTranslationKeys = {
  PDF: "documentPdf",
  BILL: "documentBill",
};

const getStoredLanguage = () => {
  const user = JSON.parse(localStorage.getItem("user") || "null");
  return user?.preferredLanguage || localStorage.getItem("preferredLanguage") || "en";
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(getStoredLanguage);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    localStorage.setItem("preferredLanguage", language);
    const user = JSON.parse(localStorage.getItem("user") || "null");
    if (user) {
      localStorage.setItem("user", JSON.stringify({ ...user, preferredLanguage: language }));
    }
  }, [language]);

  useEffect(() => {
    const syncLanguage = async () => {
      const token = localStorage.getItem("token");
      if (!token) {
        return;
      }

      try {
        const res = await API.get("/auth/me");
        const nextLanguage = res.data.preferredLanguage || "en";
        setLanguage(nextLanguage);
        localStorage.setItem("user", JSON.stringify(res.data));
      } catch {
        // fall back to local storage if profile fetch fails
      }
    };

    syncLanguage();
  }, []);

  const setLanguagePreference = async (nextLanguage, persist = false) => {
    setLanguage(nextLanguage);

    if (!persist || !localStorage.getItem("token")) {
      return;
    }

    setLoading(true);
    try {
      const res = await API.put("/auth/preferences/language", { preferredLanguage: nextLanguage });
      localStorage.setItem("user", JSON.stringify(res.data.user));
      setLanguage(res.data.user.preferredLanguage);
    } finally {
      setLoading(false);
    }
  };

  const value = useMemo(
    () => ({
      language,
      loading,
      t: (key) =>
        translations[language]?.[key]
        || supplementalTranslations[language]?.[key]
        || translations.en[key]
        || supplementalTranslations.en[key]
        || key,
      translateCategory: (category) => {
        const translationKey = categoryTranslationKeys[category];
        if (!translationKey) {
          return category;
        }

        return (
          translations[language]?.[translationKey]
          || supplementalTranslations[language]?.[translationKey]
          || supplementalTranslations.en[translationKey]
          || category
        );
      },
      translateHealthLabel: (label) => {
        const translationKey = healthTranslationKeys[label];
        if (!translationKey) {
          return label;
        }

        return (
          supplementalTranslations[language]?.[translationKey]
          || supplementalTranslations.en[translationKey]
          || label
        );
      },
      translateDocumentType: (documentType) => {
        const translationKey = documentTranslationKeys[documentType];
        if (!translationKey) {
          return documentType;
        }

        return (
          supplementalTranslations[language]?.[translationKey]
          || supplementalTranslations.en[translationKey]
          || documentType
        );
      },
      setLanguagePreference,
      supportedLanguages: SUPPORTED_LANGUAGES,
    }),
    [language, loading],
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const value = useContext(LanguageContext);

  if (!value) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }

  return value;
}
